### ISSUE TITLE
Where do I place the "game" and "lib" folders on Mac?

### ISSUE THREAD

**Issue by cherrymonika** [tw4449-s-MAS-Submods/tw4449-Custom-Room-Selection-Pack-Main-Repository#55]
On the instructions file there's written I should place them on the "DDLC.exe" folder, but I don't have it. Should they go to the "game" one? Please help me :(
For all the other submods, I put "mod assets" of the sub folder in the game one of DDLC, and that's it

**Comment by Cdino11** [comment]
From the Room.Selection.Pack folder, copy the 'game' and 'lib' folders into the main 'Doki Doki Literature Club' folder (AKA, the folder where you see 'DDLC.exe)

**Comment by RobTTM** [comment]
You're in the right place, that folder where mod assets is located is the "game" folder. You need to paste the files from game into game, and then go one folder up and paste the files from lib into lib. At least it should be, I'm not entire sure myself as I have no way of testing it due to not having a mac.

**Comment by cherrymonika** [comment]
Hi, I placed the two folders in the "autorun" one and it has worked!! Still, thank you so much for your replies, I really appreciate your help♡
